### ISSUE TITLE
对对对我是来搞笑的

### ISSUE THREAD

**Issue by huolongguo1O** [Chihaya-Yuka/Chinas-Unfair-Gaokao#3]
首先，竞赛并不是大部分学生的出路。曾经的竞赛基本上是“达到省一就保送”，然而，因为作弊的人太多，在10年前后改为了国集保送，平均每届不超过260人，这明显忽视了部分潜在的人才，并且这些人把竞赛作为跳板，比如数竞-》姚班。还有些竞赛银牌保强基（似乎必须是相同专业），但总人数也不多，银牌以下基本没啥用。所以，此次泄题事件对高考高招并没有影响。
对于教育不均衡问题，事实上，北京教育条件为吸引人才提供了优势（人才引进&积分落户），事关国家发展，所以近些年政策不会有太大调整。这也导致了北京考试不全是老北京人，还有各地来的“卷二代”。这些学生依靠“卷家长”，获得了在北京高考的资格，理应在家长的基础上考上更好的大学。在北京考上一本/211确实容易，但是到985及以上，就需要上课外班，而清北还要靠运气。有些人小学学了奥数，并取得了各种竞赛一等奖，但在初中就陨落了，中考数学优秀都难。与外地不同的是，北京更注重科学的学习方式，师资力量更强大（也是有北京户口的优势），更注重睡眠……所以北京的学生素质并不差，尽管不是第一，但也在平均以上。

**Comment by LongLiveGPCR** [comment]
所以你想说明什么？

**Comment by THZrry** [comment]
我觉得 @huolongguo1O 说的有些道理但不是很清楚，正好我也想反驳，看看我的吧 #4

**Comment by LongLiveGPCR** [comment]
> @LongLiveGPCR 挂着共产主义/社会主义的旗号复辟资本主义是可耻的，你这种行为，非蠢即坏。

笑死我了，倒反天罡是吧

**Comment by LongLiveGPCR** [comment]
> > @LongLiveGPCR 挂着共产主义/社会主义的旗号复辟资本主义是可耻的，你这种行为，非蠢即坏。
> 
> 事实上我尝试过

尝试过什么

**Comment by Chihaya-Yuka** [comment]
给 @huolongguo1O 京✌磕一个。

我和这位提交者认识，请不要离开这里，北京户口✌。

**Comment by Chihaya-Yuka** [comment]
过低的信息熵，您是语言模型吗？

**Comment by LongLiveGPCR** [comment]
什么树开什么花，什么样的阶级说什么样的话。
